language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs-v2.5.0"
  - "4.0"
  - "4.1"
branches:
  except:
    - image
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
